export const npcsData = [
  {
    firstName: "Morgan",
    lastName: "Whittlewood",
    race: "Dwarf",
    characterClass: "Cleric",
    alignment: "Neutral Good",
    demeanorTags: ["compassionate", "hopeful", "ambitious"],
    charImg: "char1.jpg",
    alt: "",
  },
  {
    firstName: "Trakian",
    lastName: "Spiritshadow",
    race: "Elf",
    characterClass: "Ranger",
    alignment: "Lawful Neutral",
    demeanorTags: ["impartial", "brave", "impatient"],
    charImg: "char2.jpg",
    alt: "",
  },
  {
    firstName: "Osver",
    lastName: "Twilightbelly",
    race: "Halfling",
    characterClass: "Thief",
    alignment: "Neutral",
    demeanorTags: ["ambitious", "playful", "adaptable"],
    charImg: "char3.jpg",
    alt: "",
  },
  {
    firstName: "Zesher",
    lastName: "Nashol",
    race: "Human",
    characterClass: "Fighter",
    alignment: "Neutral Evil",
    demeanorTags: ["dishonest", "mysterious", "ambitious"],
    charImg: "char4.jpg",
    alt: "",
  },
  {
    firstName: "Ronbar",
    lastName: "Babblehide",
    race: "Gnome",
    characterClass: "Wizard",
    alignment: "Chaotic Evil",
    demeanorTags: ["hostile", "obnoxious", "impatient"],
    charImg: "char5.jpg",
    alt: "",
  },
  {
    firstName: "Jilviel",
    lastName: "Cisti",
    race: "Half-Elf",
    characterClass: "Paladin",
    alignment: "Lawful Good",
    demeanorTags: ["brave", "generous", "impatient"],
    charImg: "char6.jpg",
    alt: "",
  },
  {
    firstName: "Tynar",
    lastName: "Mountainboot",
    race: "Dwarf",
    characterClass: "Fighter",
    alignment: "Chaotic Good",
    demeanorTags: ["brave", "hopeful", "arrogant"],
    charImg: "char7.jpg",
    alt: "",
  },
  {
    firstName: "Sarlar",
    lastName: "Futhris",
    race: "Elf",
    characterClass: "Wizard",
    alignment: "Lawful Neutral",
    demeanorTags: ["mysterious", "cowardly", "hopeful"],
    charImg: "char8.jpg",
    alt: "",
  },
  {
    firstName: "Uvibin",
    lastName: "Copperbrace",
    race: "Halfling",
    characterClass: "Bard",
    alignment: "Chaotic Neutral",
    demeanorTags: ["playful", "obnoxious", "arrogant"],
    charImg: "char9.jpg",
    alt: "",
  },
  {
    firstName: "Sanal",
    lastName: "Sesk",
    race: "Human",
    characterClass: "Warlock",
    alignment: "Lawful Evil",
    demeanorTags: ["arrogant", "impatient", "ambitious"],
    charImg: "char10.jpg",
    alt: "",
  },
  {
    firstName: "Yokini",
    lastName: "Palerest",
    race: "Gnome",
    characterClass: "Druid",
    alignment: "Lawful Good",
    demeanorTags: ["compassionate", "hopeful", "generous"],
    charImg: "char11.jpg",
    alt: "",
  },
  {
    firstName: "Ianfaelor",
    lastName: "Gritsk",
    race: "Half-Elf",
    characterClass: "Thief",
    alignment: "Neutral Good",
    demeanorTags: ["impartial", "dishonest", "compassionate"],
    charImg: "char12.jpg",
    alt: "",
  },
];
